### ISSUE TITLE
Error on cf push

### ISSUE THREAD

**Issue by mickdee** [dmikusa-pivotal/cf-ex-drupal#1]
After downloading the repo and following all configuration steps, cf push results in the following error:

"ERR The extension 'apc' is not provided by this buildpack."

The app also crashes on startup:

App instance exited with guid ecc2c23e-f788-42d3-8f0f-c44ea4c778dc payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n\* 2 error(s) occurred:\n\n\* Exited with status 1\n\* cancelled\n\* cancelled", "crash_count"=>1, "crash_timestamp"=>1469815027852427206, "version"=>"0228764f-9b72-4dac-95b4-949a29ed283f"}

**Comment by dmikusa** [comment]
You can try removing `apc` from this line in your options.json file.  That should prevent the build pack from trying and failing loading it.

https://github.com/dmikusa-pivotal/cf-ex-drupal/blob/master/.bp-config/options.json#L2

Let me know how things go from there.  I haven't updated / used this project in a while so there maybe some other issues to work though.  Happy to help you work through them though.

**Comment by mickdee** [comment]
Thanks for your help! Still no dice, though - after removing `apc` from options.json

A couple things in the logs that might help:

[OUT] 17:49:03 httpd | Invalid command 'RequestHeader', perhaps misspelled or defined by a module not included in the server configuration
[OUT] 17:49:03 httpd | AH00526: Syntax error on line 15 of /home/vcap/app/httpd/conf/httpd.conf:

[OUT] App instance exited with guid e3689520-3641-4d25-af98-17a1bc6f86a1 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n\* 2 error(s) occurred:\n\n\* Exited with status 1\n\* cancelled\n\* cancelled", "crash_count"=>2, "crash_timestamp"=>1470678544071974138, "version"=>"ff7f5041-c3a6-48ee-a5c4-df29bc214009"}

**Comment by dmikusa** [comment]
OK, I think I've fixed that.

https://github.com/dmikusa-pivotal/cf-ex-drupal/blob/master/.bp-config/httpd/extra/httpd-modules.conf#L15-L17

The file referenced at that link is used to add an additional HTTPD module.  It got out-of-sync with what was being used by the build pack, so the build pack's default config needed some additional modules.  I added those in and that should clear up the error above.

For what it's worth, you could probably just remove the `.bp-config/httpd` folder and everything below it.  I think that all it's doing is adding this module.

https://github.com/dmikusa-pivotal/cf-ex-drupal/blob/master/.bp-config/httpd/extra/httpd-modules.conf#L18

I'm not sure if that is needed any more.  It's a compatibility module so that HTTPD 2.4 can use the HTTPD 2.2 style access controls.  Assuming that Drupal is compatible with HTTPD 2.4, this would no longer be necessary and would simplify things here.

**Comment by dmikusa** [comment]
Closing this out.  If you need more help, open a new issue.
