### ISSUE TITLE
error on accessing install script

### ISSUE THREAD

**Issue by nibedita-giri** [dmikusa-pivotal/cf-ex-drupal#2]
After cf push when i am trying to access install script getting 500 internal server error 

/home/vcap/app/htdocs/.htaccess: Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration, referer: http://hostname.sys_domain.com/install.php

I am using php-buildpack v4.3.19 - https://github.com/cloudfoundry/php-buildpack

**Comment by dmikusa** [comment]
Do you have this file in your project?  It should pull in the access compat module, which is what the error is complaining about.  

https://github.com/dmikusa-pivotal/cf-ex-drupal/blob/master/.bp-config/httpd/extra/httpd-modules.conf#L18

Other option is to fix the `.htaccess` file so it's compatible with HTTPD 2.4.  I assume that file is coming from Drupal though, so it may not be an easy fix.

**Comment by nibedita-giri** [comment]
Yes, i am using this repository to push the app and it does contain mod_access_compat module.

**Comment by dmikusa** [comment]
My suggestion would be to `cf ssh` to your application instances and then `cd` into the `app/httpd/conf/extra` directory and look at the `httpd-modules.conf` configuration file.  Make sure it has the `access_compat_module` listed.  If that's not listed then you'd get the error above.  If it's not listed, then the question would be why isn't is listed since it's in the files you're pushing.  To help with that, you'd need to set the `BP_DEBUG` environment variable to `True` and restage the app.  That will give more details from the build pack at staging and should hopefully show why it's not configuring HTTPD properly.

**Comment by nibedita-giri** [comment]
when i first ssh into the app i can see access_comapct module was not enabled . After re-staging the app it seems to work fine.

Thanks for the help.
